### PR TITLE
Bugfix/84

### PR DESCRIPTION
**Pull request by efbenson**
changes how the query code works to keep existing manipulation, but allowing for limit/offset/order to be done by alasql

### CODE REVIEW

**Comment by efbenson** [comment]
Ill take a look at those build issues in the morning

**Comment by rgwozdz** [comment]
@efbenson tests are failing because the new code doesn't conform to standard.js

**Comment by rgwozdz** [comment]
When your first issue was logged I started looking into a post-query iterative sort.  Sorry, I didn't realize you had already started an effort.  My WIP PR is here: https://github.com/koopjs/winnow/pull/86

**Comment by efbenson** [comment]
Problem with post ordering outside the alasql is that you will have to disregard limit and process the whole feature set to make sure you order correctly. This is something brought up by it client as they use koop in AGOL and need to sort layers that are paginated.

**Comment by rgwozdz** [comment]
At least right now, the limit isn't used in the SQL, because as you mentioned the SQL is being applied on a per feature basis.  So I think one way forward would be to apply the sort (if `options.orderByFields` is defined) prior to these loops https://github.com/koopjs/winnow/blob/master/src/executeQuery.js#L36-L41, https://github.com/koopjs/winnow/blob/master/src/executeQuery.js#L55-L59.  If the feature set is big, that could be an expensive sort, but I'd big curious if it's any more expensive than what alasql is doing under the hood. @dmfenton any additional thoughts?

**Comment by rgwozdz** [comment]
After more thought on this, we might the approach of capturing the essentially of the `esriFy` function and pass it in as part of the `pick` function in the SQL statement.

**Comment by rgwozdz** [comment]
Moved the esriFy to the SQL and then was able to let SQL handle ORDER, LIMIT, OFFSET in https://github.com/koopjs/winnow/pull/90.  Released in v1.6.1

**Pull request closed without merging**
