### PR TITLE
Queries on heroku were broken

### PR DESCRIPTION
**Pull request by mishugana**
On heroku, queries were broken by farmhash's binary not loading correctly and the try catch not finding it.
I added a line to test farmhash and on systems where the issue exists, it should instead use the other hashing algo, which works correctly.

### CODE REVIEW

**Review by rgwozdz — CHANGES_REQUESTED** [review]
@mishugana thanks so much for finding and fixing!  It's failing the linting test (see Travis failure).  Running `standard --fix` on your branch should remove the lint.  If you could do this and add an entry to the CHANGELOG under ## Unreleased, I'll merge and publish.

**Comment by mishugana** [comment]
Awesome! I put in those changes, let me know if you need me to do anything else.

**Comment by rgwozdz** [comment]
Merged, thanks @mishugana! Will release this shortly.

**Comment by rgwozdz** [comment]
winnow 2.0.2 released and published to npm.

**Pull request merged**
